version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_personal
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: personal_trainer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - personal_net

volumes:
  postgres_data:

networks:
  personal_net:
